### ISSUE TITLE
Update / Add Environment Variables for Harvest

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/lux_tracking#6]
Update:
```
VOYAGER_DB_CONNECTIONSTRING=jdbc:oracle:thin:@yul-vgr-rpt1.library.yale.internal:1521:VGER
```
Add:
```
ILS_HARVEST_THREADCOUNT=30
VOYAGER_DB_MAXIMUMPOOLSIZE=35
```

**Comment by kbcarter** [comment]
I meant to update this ticket sooner but I've added the two environment variables to the AWS and in the container definition

![image.png](https://images.zenhubusercontent.com/5e6002742347da559ce428f3/4beba013-0faa-4b10-98b4-bf64ceae21ba)

![image.png](https://images.zenhubusercontent.com/5e6002742347da559ce428f3/23e70077-d756-4c73-acab-e6a16499276b)
